# Generated by Django 3.0.1 on 2019-12-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HighScore',
            new_name='Player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player',
            new_name='name',
        ),
    ]
