# Generated by Django 3.0.1 on 2019-12-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191228_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(),
        ),
    ]
